### ISSUE TITLE
links to talk and survey are broken

### ISSUE THREAD

**Issue by memming** [marciogameiro/CMGDB#1]
The two links in the README
http://chomp.rutgers.edu/Projects/survey/cmdbSurvey.pdf
http://chomp.rutgers.edu/Projects/Databases_for_the_Global_Dynamics/software/LorentzCenterAugust2014.pdf
are returning 404 not found.

Could you add these resources to this git repo or reupload somewhere else? Thank you.

**Comment by GuillaumeGirier** [comment]
I up this post, because indeed, it is also not possible to access the documentation.
It could be very interesting to have them to understand how to use the functions!

Have a great day.

**Comment by marciogameiro** [comment]
I updated the links, but keep in mind that those resources are outdated. The notebooks in the examples folder may be a better resource to understand how to use the code.
